name: example

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: git init
      - name: second step
        run: git remote set-url SAP-DI https://github.com/nktsharma28/SAP-DI.git

