name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'nktsharma28'
          git config --global user.email 'nktsharma28@gmail.com'
          git commit -am "Automated report"
          git push
